version: '3.4'

services:
  foxbetesta.api:
    image: ${DOCKER_REGISTRY-}foxbetestaapi
    build:
      context: .
      dockerfile: FoxBeTestA.Api/Dockerfile  
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Initial Catalog=FoxBeTestAApi;Data Source=sqldb;Persist Security Info=True;User ID=SA;Password=2Secure*Password2

  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - SA_PASSWORD=2Secure*Password2
        - ACCEPT_EULA=Y
    ports:
        - "1440:1433"
